"""recreate cars and parking_records

Revision ID: 50b06f8367da
Revises: 
Create Date: 2025-10-11 02:43:35.978576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b06f8367da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_records',
                  sa.Column('plate_number', sa.String(length=32), nullable=False, server_default='UNKNOWN')
                  )
    op.create_index(op.f('ix_parking_records_plate_number'), 'parking_records', ['plate_number'], unique=False)
    op.drop_column('parking_records', 'car_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_records', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_parking_records_plate_number'), table_name='parking_records')
    op.drop_column('parking_records', 'plate_number')
    # ### end Alembic commands ###
