const API = {
  base: "http://localhost:8000",  // FastAPI backend adresi
  wsBase: "ws://localhost:8000",
  manualEntry: "/api/manual_entry",
  uploadImage: "/api/upload/image",
  getRecords: "/api/parking_records",
  getRecordsByPlate: (plate) => `/api/parking_records/by_plate/${encodeURIComponent(plate)}`,
  createRecord: "/api/parking_records",
  completeRecord: (recordId) => `/api/parking_records/${recordId}/exit`,
  updatePlate: (recordId) => `/api/parking_records/${recordId}/plate`,
  deleteRecord: (recordId) => `/api/parking_records/${recordId}`,
  recordsStream: "/ws/parking_records",
  login: "/api/login",
  superAdminLogin: "/api/super_admin/login",
  userLogin: "/api/user_login",
  userRecognizePlate: "/api/user/recognize_plate",
  listUsers: "/api/users",
  changeUserPassword: (userId) => `/api/users/${userId}/password`,
  createUser: "/api/users",
  updateUser: (userId) => `/api/users/${userId}`,
  deleteUser: (userId) => `/api/users/${userId}`,
  forgotPassword: "/api/forgot-password",
  resetPassword: "/api/reset-password",
  verifyResetToken: (token) => `/api/verify-reset-token/${token}`,
  updateMyInfo: "/api/users/me/update",
  createPayment: "/api/payments",
  getPaymentQR: (paymentId) => `/api/payments/${paymentId}/qr`,
  confirmPayment: (paymentId) => `/api/payments/${paymentId}/confirm`,
  autoConfirmPayment: (paymentId) => `/api/payments/${paymentId}/auto-confirm`,
};

export default API;
